/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ConfirmModal: typeof import('./../components/ConfirmModal.vue')['default']
    ConstructButton: typeof import('@sa-net/components')['ConstructButton']
    ConstructInput: typeof import('@sa-net/components')['ConstructInput']
    ConstructLayout: typeof import('@sa-net/components')['ConstructLayout']
    ConstructLink: typeof import('@sa-net/components')['ConstructLink']
    ConstructMenu: typeof import('@sa-net/components')['ConstructMenu']
    ConstructPage: typeof import('@sa-net/components')['ConstructPage']
    ConstructTabs: typeof import('@sa-net/components')['ConstructTabs']
    ConstructTextArea: typeof import('@sa-net/components')['ConstructTextArea']
    ConstructTitle: typeof import('@sa-net/components')['ConstructTitle']
    LoadingScreen: typeof import('./../components/LoadingScreen.vue')['default']
    NavigationSidebar: typeof import('./../components/Navigation/Sidebar.vue')['default']
    ReportActions: typeof import('./../components/Report/Actions.vue')['default']
    ReportCreated: typeof import('./../components/Report/Created.vue')['default']
    ReportDescription: typeof import('./../components/Report/Description.vue')['default']
    ReportEditButton: typeof import('./../components/Report/EditButton.vue')['default']
    ReportID: typeof import('./../components/Report/ID.vue')['default']
    ReportProvider: typeof import('./../components/Report/Provider.vue')['default']
    ReportRemoveButton: typeof import('./../components/Report/RemoveButton.vue')['default']
    ReportTitle: typeof import('./../components/Report/Title.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TabView: typeof import('./../components/TabView.vue')['default']
  }
}
