/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ConstructButton: typeof import('@sa-net/components')['ConstructButton']
    ConstructInput: typeof import('@sa-net/components')['ConstructInput']
    ConstructLayout: typeof import('@sa-net/components')['ConstructLayout']
    ConstructLink: typeof import('@sa-net/components')['ConstructLink']
    ConstructMenu: typeof import('@sa-net/components')['ConstructMenu']
    ConstructPage: typeof import('@sa-net/components')['ConstructPage']
    ConstructTextArea: typeof import('@sa-net/components')['ConstructTextArea']
    LoadingScreen: typeof import('./../components/LoadingScreen.vue')['default']
    NavigationSidebar: typeof import('./../components/Navigation/Sidebar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
